version: "3.8"

services:
  app-deployment:
    image: zerosuxx/nodejs-example-app:0.1.0
    entrypoint: "node"
    command: "index.js"
    labels:
     kompose.service.expose: "nodejs-example-app.zer0.hu"
     kompose.service.expose.ingress-class-name: "nginx"
     nginx.ingress.kubernetes.io/ssl-redirect: "false"
    ports:
      - "3000:3000"
    environment:
      APP_ENV: "staging"
      AUTH_TOKEN: "t0k3n"