version: "3.8"

services:
  app-deployment:
    image: zerosuxx/nodejs-example-app:0.1.0
    entrypoint: "node"
    command: "index.js"
    environment:
      APP_ENV: "staging"
      AUTH_TOKEN: "t0k3n"