apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-deployment.yaml --replicas 2 --out 2-kompose-deployment
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: app-deployment
  name: app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: app-deployment
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-deployment.yaml --replicas 2 --out 2-kompose-deployment
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/nodejs-example-app-default: "true"
        io.kompose.service: app-deployment
    spec:
      containers:
        - args:
            - index.js
          command:
            - node
          env:
            - name: APP_ENV
              value: staging
            - name: AUTH_TOKEN
              value: t0k3n
          image: zerosuxx/nodejs-example-app:0.1.0
          name: app-deployment
      restartPolicy: Always
