apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --out kompose-deployment/ --controller deployment --replicas 2
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: app2
  name: app2
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    io.kompose.service: app2
