apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert --out kompose-pod/
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.network/nodejs-example-app-default: "true"
    io.kompose.service: app
  name: app
spec:
  containers:
    - args:
        - index.js
      command:
        - node
      env:
        - name: APP_ENV
          value: staging
        - name: AUTH_TOKEN
          value: t0k3n
      image: zerosuxx/nodejs-example-app:0.1.0
      name: app
      ports:
        - containerPort: 3000
          hostPort: 3000
          protocol: TCP
  restartPolicy: OnFailure
