apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml --out 1-kompose-pod
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.network/nodejs-example-app-default: "true"
    io.kompose.service: app-pod
  name: app-pod
spec:
  containers:
    - args:
        - index.js
      command:
        - node
      env:
        - name: APP_ENV
          value: staging
        - name: AUTH_TOKEN
          value: t0k3n
      image: zerosuxx/nodejs-example-app:0.1.0
      name: app-pod
  restartPolicy: OnFailure
